# -*- mode: ruby -*-
# vi: set ft=ruby :

begin
        Vagrant.require_version ">= 2.0.1"
        COMPAT=""
rescue
        print("note: Current version of Vagrant is not support BOX with /etc/net.\n      Please, update Vagrant to version greater than 2.0.1\n")
        Vagrant.require_version "<= 1.9.4"
        COMPAT="true"
end

#Box Windows Server 2008 r2 for AD DC Forest

#Fix deprecated option Issues #4349
#Vagrant.require_plugin "vagrant-reload"

REQUIRED_PLUGINS = %w(vagrant-reload)

#Base BOX
#universalvishwa/windows-2008-r2-standard-x64

Vagrant.configure("2") do |config|
  config.vm.box = "universalvishwa/windows-2008-r2-standard-x64"

  config.vm.hostname = "win08r2srv-dc1"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true

    config.vm.communicator = "winrm"

    config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    config.vm.network :private_network, ip: "192.168.38.2", gateway: "192.168.38.1"

  config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.38.2"
  config.vm.provision "shell", path: "scripts/provision-dc.ps1", privileged: false
  config.vm.provision :reload

end
