# -*- mode: ruby -*-
# vi: set ft=ruby :

REQUIRED_PLUGINS = %w(vagrant-reload)

Vagrant.configure("2") do |config|
  config.vm.box = "universalvishwa/windows-2008-r2-standard-x64"

  config.vm.hostname = "win08r2srv-test2"

  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.vm.communicator = "winrm"

  config.vm.provider "virtualbox" do |vb, override|
    vb.customize ["modifyvm", :id, "--memory", 1024]
    vb.customize ["modifyvm", :id, "--cpus", 1]
    vb.customize ["modifyvm", :id, "--vram", "32"]
    vb.name = config.vm.hostname
  end

  config.vm.network :private_network, ip: "192.168.56.251", gateway: "192.168.56.1", virtualbox__intnet: "intnet"

  config.vm.provision "shell", path: "scripts/fix-dns.ps1", privileged: false, args: "192.168.56.2"
  #config.vm.provision :reload

  #config.vm.provision "shell", path: "scripts/join-domain.ps1", privileged: true
  #config.vm.provision "shell", path: "scripts/sysprep.ps1", privileged: true
  #config.vm.provision :reload

end
