# Start VM Windows Server 2008 r2 for AD DC Forest + Child
# (c) Georgy A Bystrenin gkot@altlinux.org 16 Janury 2018
# Base BOX universalvishwa/windows-2008-r2-standard-x64
###########
# Install :
# vagratn up dc - start Domain Controller domain.alt
# vagratn up child - start Domain Controller subdomain child.domain.alt

# -*- mode: ruby -*-
# vi: set ft=ruby :

#Check version Vagrant
begin
        Vagrant.require_version ">= 2.0.1"
        COMPAT=""
rescue
        print("note: Current version of Vagrant is not support BOX with /etc/net.\n      Please, update Vagrant to version greater than 2.0.1\n")
        Vagrant.require_version "<= 1.9.4"
        COMPAT="true"
end

#Add plugins reload
REQUIRED_PLUGINS = %w(vagrant-reload)
plugins_to_install = REQUIRED_PLUGINS.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Not installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

#Prefix to Basename VM
basename = "win08r2s"

#Base BOX
basebox = "universalvishwa/windows-2008-r2-standard-x64"

Vagrant.configure("2") do |config|

  # Use all the plaintext WinRM transport and force it to use basic authentication.
  config.winrm.transport = :plaintext
  config.winrm.basic_auth_only = true
  config.vm.communicator = "winrm"

  #AD DC Forest
  config.vm.define "dc" do |cfg|
    cfg.vm.box = basebox
    cfg.vm.hostname = basename + "-dc3"

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.name = cfg.vm.hostname
    end

    cfg.vm.network :forwarded_port, guest: 5985, host: 9531, id: "winrm", auto_correct: true
    #cfg.vm.network :forwarded_port, guest: 5986, host: 9631, auto_correct: true
    cfg.vm.network :forwarded_port, guest: 22, host: 2231, id: "ssh", auto_correct: true
    cfg.vm.network :forwarded_port, guest: 3389, host: 3831, id: "rdp", auto_correct: true

    cfg.vm.network :private_network, ip: "192.168.38.31", gateway: "192.168.38.1"

    cfg.vm.provision "shell", path: "scripts/create-domain-2008r2.ps1", privileged: false
    cfg.vm.provision :reload
  end

  #Child controller
  config.vm.define "child" do |cfg|
    cfg.vm.box = basebox
    cfg.vm.hostname = basename + "-dc3ch"

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      vb.name = cfg.vm.hostname
    end

    cfg.vm.network :forwarded_port, guest: 5985, host: 9532, id: "winrm", auto_correct: true
    #cfg.vm.network :forwarded_port, guest: 5986, host: 9632, auto_correct: true
    cfg.vm.network :forwarded_port, guest: 22, host: 2232, id: "ssh", auto_correct: true
    cfg.vm.network :forwarded_port, guest: 3389, host: 3832, id: "rdp", auto_correct: true

    cfg.vm.network :private_network, ip: "192.168.38.32", gateway: "192.168.38.1", dns: "192.168.38.31"

    cfg.vm.provision "shell", path: "scripts/sysprep.ps1", privileged: true

    sleep 10
    cfg.vm.provision :reload

    cfg.vm.provision "shell", path: "scripts/fix-dns.ps1", privileged: false, args: "192.168.38.31"
    cfg.vm.provision "shell", path: "scripts/add-child-domain-2008r2.ps1", privileged: false
    sleep 10
  end
end
