# -*- mode: ruby -*-
# vi: set ft=ruby :

begin
        Vagrant.require_version ">= 2.0.1"
        COMPAT=""
rescue
        print("note: Current version of Vagrant is not support BOX with /etc/net.\n      Please, update Vagrant to version greater than 2.0.1\n")
        Vagrant.require_version "<= 1.9.4"
        COMPAT="true"
end

#Fix deprecated option Issues #4349
#Vagrant.require_plugin "vagrant-reload"

REQUIRED_PLUGINS = %w(vagrant-reload)

#Windows Server 2008 r2 for AD DC Forest + Replica

basename = "win08r2srv"

#Base BOX
#universalvishwa/windows-2008-r2-standard-x64
basebox = "universalvishwa/windows-2008-r2-standard-x64"

Vagrant.configure("2") do |config|

    # use the plaintext WinRM transport and force it to use basic authentication.
    # NB this is needed because the default negotiate transport stops working
    #    after the domain controller is installed.
    #    see https://groups.google.com/forum/#!topic/vagrant-up/sZantuCM0q4
    config.winrm.transport = :plaintext
    config.winrm.basic_auth_only = true

    config.vm.communicator = "winrm"

  #AD DC Forest
  config.vm.define "dc" do |config|
    config.vm.box = basebox
    config.vm.hostname = basename + "-dc2"

    config.vm.provider "virtualbox" do |vb, override|
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    config.vm.network :forwarded_port, guest: 5985, host: 5982, id: "winrm", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true
    config.vm.network :forwarded_port, guest: 3389, host: 3382, id: "rdp", auto_correct: true
    config.vm.network :private_network, ip: "192.168.38.2", gateway: "192.168.38.1"

    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "192.168.38.2"
    config.vm.provision "shell", path: "scripts/provision-dc.ps1", privileged: false
    config.vm.provision :reload
  end

  #Replica
  config.vm.define "repl" do |config|
    config.vm.box = basebox
    config.vm.hostname = basename + "-dc2repl"

    config.vm.provider "virtualbox" do |vb, override|
      vb.customize ["modifyvm", :id, "--memory", 1024]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--vram", "32"]
      #vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    config.vm.network :forwarded_port, guest: 5985, host: 5983, id: "winrm", auto_correct: true
    config.vm.network :forwarded_port, guest: 22, host: 2223, id: "ssh", auto_correct: true
    config.vm.network :forwarded_port, guest: 3389, host: 3383, id: "rdp", auto_correct: true
    config.vm.network :private_network, ip: "192.168.38.3", gateway: "192.168.38.1", dns: "192.168.38.2"

    config.vm.provision "shell", path: "scripts/fix-second-network.ps1", privileged: false, args: "-ip 192.168.38.3 -dns 192.168.38.2"
    config.vm.provision "shell", path: "scripts/provision-repl.ps1", privileged: false
    config.vm.provision :reload
  end

end
